name: shifts
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  intl: ^0.17.0
  geocoding: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true
  assets:
    - assets/offered_shifts.json
    - assets/images/
